export const SIGN_UP_SUCCESS_ALERT = 'SIGN_UP_SUCCESS_ALERT';
export const SIGN_UP_ERROR_ALERT = 'SIGN_UP_ERROR_ALERT';

export const SIGN_IN_SUCCESS_ALERT = 'SIGN_IN_SUCCESS_ALERT';
export const SIGN_IN_ERROR_ALERT = 'SIGN_IN_ERROR_ALERT';

export const SIGN_OUT_SUCCESS_ALERT = 'SIGN_OUT_SUCCESS_ALERT';