export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const REGISTERED_TYPE = 'REGISTERED_TYPE';
export const APPLICATION_TYPE = 'APPLICATION_TYPE';

export const FETCH_AUTH_USER_LOADING = 'FETCH_AUTH_USER_LOADING';
export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS';
export const FETCH_AUTH_USER_FAIL = 'FETCH_AUTH_USER_FAIL';