export const FETCH_RESEARCHES_REQUEST = 'FETCH_RESEARCHES_REQUEST';
export const FETCH_RESEARCHES_SUCCESS = 'FETCH_RESEARCHES_SUCCESS';
export const FETCH_RESEARCHES_FAIL = 'FETCH_RESEARCHES_FAIL';

export const CREATE_RESEARCH_REQUEST = 'CREATE_RESEARCH_REQUEST';
export const CREATE_RESEARCH_SUCCESS = 'CREATE_RESEARCH_SUCCESS';
export const CREATE_RESEARCH_FAIL = 'CREATE_RESEARCH_FAIL';