export const OPEN_ROOM = 'OPEN_ROOM';
export const SET_ROOM_DETAILS = 'SET_ROOM_DETAILS';
export const SET_ACTIVE_ROOMS = 'SET_ACTIVE_ROOMS';
export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_REMOTE_STREAMS = 'SET_REMOTE_STREAMS';
export const SET_AUDIO_ONLY = 'SEY_AUDIO_ONLY';